version: '3'

services:
  db:
    image: postgres:latest
    container_name: project2-db
    restart: always
    ports:
      - "5430:5432"
    volumes:
      - dbdata:/data/postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=app
      - POSTGRES_DB=app
    networks:
      - project2_network

networks:
  project2_network:
    driver: bridge
volumes:
  dbdata: